version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://teste-olhar180-backend.onrender.com/api/v1}
    container_name: taskmanager-frontend
    ports:
      - "8081:80"
    restart: unless-stopped